
export const tipoMap = {
	Planeta: 1,
	Continente: 2,
	Pais: 3,
	Regiao: 4,
	Estado: 5,
	Estado_Div_1: 6,
	Estado_Div_2: 7,
	Municipio: 8,
	Distrito: 9,
	Bairro: 10,
	Logradouro: 11,
	Numero: 12,
	Complemento: 13,
}
export const paisBrasil = {
	id: 3,
	sigla: 'BRA',
	nome: 'Brasil',
}
export const paisRegiaoMap = {
	'1': { sigla: 'N', nome: 'Norte' },
	'2': { sigla: 'NE', nome: 'Nordeste' },
	'3': { sigla: 'SE', nome: 'Sudeste' },
	'4': { sigla: 'S', nome: 'Sul' },
	'5': { sigla: 'CO', nome: 'Centro-Oeste' },
}
export const estadosMap = {
	'11': { sigla: 'RO' },
	'12': { sigla: 'AC' },
	'13': { sigla: 'AM' },
	'14': { sigla: 'RR' },
	'15': { sigla: 'PA' },
	'16': { sigla: 'AP' },
	'17': { sigla: 'TO' },
	'21': { sigla: 'MA' },
	'22': { sigla: 'PI' },
	'23': { sigla: 'CE' },
	'24': { sigla: 'RN' },
	'25': { sigla: 'PB' },
	'26': { sigla: 'PE' },
	'27': { sigla: 'AL' },
	'28': { sigla: 'SE' },
	'29': { sigla: 'BA' },
	'31': { sigla: 'MG' },
	'32': { sigla: 'ES' },
	'33': { sigla: 'RJ' },
	'35': { sigla: 'SP' },
	'41': { sigla: 'PR' },
	'42': { sigla: 'SC' },
	'43': { sigla: 'RS' },
	'50': { sigla: 'MS' },
	'51': { sigla: 'MT' },
	'52': { sigla: 'GO' },
	'53': { sigla: 'DF' },
}
